deployment:
  tasks:
    - export DEPLOYPATH=/home/tiruinter/public_html
    - /bin/rsync -av --delete --exclude='.git/' --exclude='.github/' --exclude='.env' --exclude='admin/.env' --exclude='public/uploads/' --exclude='public/resume/' --exclude='storage/' --exclude='node_modules/' public_html/ "$DEPLOYPATH/"