@extends('layout.app')
@section('content')

@php
$bannerbg = Helper::bannerimg();
$settings = DB::table('settings')->first();
@endphp

    <!-- Banner -->
    
    {!! $bannerbg !!}
	
    <!-- /Banner -->


    <section class="section-content">
        <div class="container-fluid">
            <div class="col-md-10 offset-1">
                
                {!! $settings->terms_and_conditions !!}
		
		    </div>
		</div>
	</section>
		


		<!--    <section>-->
		<!--    <div class="container-fluid" style="background-color:azure">-->
		<!--        <div  class="heading" >-->
		<!--        <h3>Terms And Conditions Of Company</h3>-->
		<!--        </div>-->
		<!--    </div>-->
		<!--    </section>-->
		<!--    <section style="background-color:white">-->
		<!--        <div class="container-fluid" style="background-color:white;width:100%;padding:10px;">-->
		<!--            <div style="background-color:#d3e1f3;width:95%;padding:5px;">-->
		<!--                <ul>-->
		<!--                    <li>The LICENSOR is the owner of copyright and all other intellectual property rights in the SOFTWARE. No verbal commitment are entertained in any manners.</li>-->
		<!--                    <li>The LICENSOR grants to the CUSTOMER/AGENT, a non-exclusive license to use the SOFTWARE, upon the terms and conditions contained hereinafter.</li>-->
		<!--                    <li>The CUSTOMER/AGENT, by opening and installing this package, is deemed to have read, understood and agreed to be bound by the terms of this Agreement.  It is also agreed that this agreement is the complete and exclusive statement of agreement between the CUSTOMER/AGENT and the LICENSOR.</li>-->
		<!--                    <li>The CUSTOMER/AGENT shall not decompile, disassemble or otherwise modify the SOFTWARE, except as provided for by this license. However, the customer can ask to Principal/Licensor for Source-Code +Database to Internal Access, It’s not intended to use for reseller/Business Use of this Product for Other Hospital apart from mentioned a above Hospital License.</li>-->
		<!--                    <li>The CUSTOMER/AGENT is solely responsible for determining the suitability of the SOFTWARE for the purpose it is intended to be used, before the purchase of the SOFTWARE.  Once the CUSTOMER/AGENT purchases the SOFTWARE, the LICENSOR will not accept return of SOFTWARE under any circumstances, whatsoever, and the payment once made shall be non-refundable. CUSTOMER/AGENT are requested to release All Dues (Payment) on time to receive Service & Support on Time. Delayed Payment of Any Respective Service/Product May lead to penalty or RoI of 5.00% /Day interest.</li>-->
		<!--                    <li>The LICENSOR does not extend and expressly disclaims any warranty, whatsoever, as to the suitability, applicability, fitness, merchantability or otherwise of the SOFTWARE and related items.</li>-->
		<!--                    <li>The SOFTWARE is offered in various editions.  Each edition is available in one or more of three different variants - Single-user, Multi-user and Client-Server.  In case of Single-user / Client-Server, the CUSTOMER/AGENT can install the SOFTWARE on a single Computer only.  In case of Multi-user, the CUSTOMER/AGENT can install the SOFTWARE on a single Local Area Network (LAN).</li>-->
		<!--                    <li>The Onsite Training will be held in Office Hrs. (9:30 AM-7:00 PM), meantime 1-Hr. Lunch time applicable (1:00pm-2:00 Pm), & Onsite Service Visit (Free-Visit) will have to repair software only, no Training included. All Customization/Development Work done at Tirupati Software Head Office Only no Customer Side Development work done.</br>The Licensor Does not guaranty of Hospital /Lab/Pharmacy/Unit for any Financial Damage/ Loss if user misuse of same with software compromises with admin access/ wrong input that leads to wrong output/ customer are strictly advised to check timely sudden inspection of HMS Software as well as user Input & tally themselves their Balance-sheet/Accounts/Data-Sheet generated by software & Such Losses will not borne/ entertained by Licensor in any manners.</li>-->
		<!--                    <li>The LICENSOR provides the warranty for all physical items (Media / Security Device) in the SOFTWARE PACKAGE for one year from the date of purchase, provided the fault in the item is specifically due to defect in material or workmanship and is not caused due to intentional or negligent acts or omission of the CUSTOMER/AGENT.  The CUSTOMER/AGENT shall be liable to present the proof of purchase at the time of request for repair / replacement to avail warranty.  Whether the faulty item needs to be repaired or replaced is the sole discretion of the LICENSOR.</li>-->
		<!--                    <li>After the warranty period of one year, AMC/ Renewal @ _________00% for software service & support shall be chargeable (Optional).All Service /AMC/ Support Cost would Revised after 3-yrs with Respective 10.00%  as a inflation Charges  of last cost. All Customer has to Paid as Respective Updated Prices for Future Service/ Past Service Availed</li>-->
		<!--                    <li>Under no circumstances, the LICENSOR shall replenish the Security Device if the same is lost / misplaced / destroyed, either intentionally or accidentally, by the CUSTOMER/AGENT.  In such a case, a new copy of the SOFTWARE needs will be Free of cost if Client’s SOFTWARE has under Warranty period/ AMC periods. By the CUSTOMER/AGENT, </li>-->
		<!--                    <li>The price of the SOFTWARE is the license fee for use of the SOFTWARE only. No lifetime Warranty consider, warranty only of AMC after customer pay Annual maintenances charge.</li>-->
		<!--                    <li>Upgrades, enhancements, additions and improved versions of the SOFTWARE shall be available to the CUSTOMER/AGENT upon Free of Cost under warranty periods/ AMC period / as per the policy of the LICENSOR, as may be prevalent from time to time.</li>-->
		<!--                    <li>After a new version is released, all further development / debugging will be carried out on the new version only, which may be subject to acceptance of further terms and conditions between the parties. (Free of Cost).</li>-->
		<!--                    <li>The LICENSOR does not guarantee the compatibility of the SOFTWARE and / or the Security Device with future Operating Systems / Technologies.</li>-->
		<!--                    <li>The LICENSOR shall not take any responsibility for any kind of corruption of data at the CUSTOMER/AGENT site due to media failure / power failure / hardware problem / virus infection or any other reason.  At most, the LICENSOR can try to recover the data either fully or partially & it will be Free of Cost only client is under AMC/Warranty Periods.</li>-->
		<!--                    <li>It is expressly agreed by the CUSTOMER/AGENT that neither the manufacturer nor the supplier of the SOFTWARE shall be liable for any loss or damage, whether direct, indirect, special, consequential and / or incidental, arising from the use or application of the SOFTWARE and related items.</li>-->
		<!--                    <li>The Statutory Reports provided in the SOFTWARE are intended to provide the information / data to the CUSTOMER/AGENT, which is required for fulfilling of various statutory obligations like depositing of tax, filing of tax returns etc.  The LICENSOR does not guarantee, promise or claim accuracy, completeness or adequacy of the information provided and makes no claim that the Statutory Reports provided in the SOFTWARE will be accepted by the tax authorities as it is.  The Licensor shall not be responsible for any error / omission or delay in fulfilling of statutory obligations by the CUSTOMER/AGENT.  In case there is any change in statutory requirement, the LICENSOR shall try to incorporate the same in the forthcoming releases of the SOFTWARE, but, shall be under no obligation to do so.</li>-->
		<!--                    <li>Tirupati Software InfotechPvt. Ltd. (Licensor) can guaranty for customer data privacy / security only that Licensor does not use any Patient/Doctor/ Staff personal information/ Financial Information & no used for any financial/Business use without written permission from Customer. We use VPS/AWS server for Cloud based/Online Version of software, & If customer has offline Version of Server then Licensor will not responsible.</li>-->
		<!--                    <li>The parties hereby agree that the courts at Jaipur (Rajasthan) for Indian Clients/ For Foreign Client Jurisdiction Area will beThe High Court of Rajasthan, Jaipur, Raj./ The Supreme court of India, New, Delhi shall have the jurisdiction to entertain any proceedings in respect of anything arising under this agreement.</li>-->
		<!--                </ul>-->
		<!--                </div>-->
		<!--        </div>-->
		<!--</section>-->
	


@endsection
